services:
  postgresql:
    container_name: postgres
    image: postgres:15.7
    ports:
      - '${DB_PORT:-5432}:5432'
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-its-nestjs}
      POSTGRES_DB: ${DB_DATABASE:-its-nestjs}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '${REDIS_PORT:-6379}:6379'
    restart: always
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
