services:
  mongodb:
    container_name: mongodb
    image: mongo:8-noble
    restart: always
    ports:
      - '${MONGO_PORT:-27017}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-its-nestjs}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-its-nestjs}
    volumes:
      - mongo-data:/data/db
      - ./src/database/database.init.js:/docker-entrypoint-initdb.d/database.init.js:ro

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - '${REDIS_PORT:-6379}:6379'
    restart: always
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data:
