x-templates:
  api: &api
    image: its-nestjs-api
    build:
      context: .
    logging:
      driver: json-file
      options:
        max-size: '10m'
        max-file: '3'
    restart: always
    env_file: .env
    depends_on:
      - redis
      - mongodb

services:
  reverse-proxy:
    image: traefik:v3.4
    container_name: reverse-proxy
    command:
      - --providers.docker
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.letsencrypt.acme.email=vutx@iceteasoftware.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./acme.json:/acme.json:rw

  api:
    <<: *api
    expose:
      - 3333
    command: sh -c "node src/main.js"
    container_name: api
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=Host(`jasperisme.io.vn`) && PathPrefix(`/api`)'
      - 'traefik.http.routers.api.entrypoints=websecure'
      - 'traefik.http.routers.api.tls.certresolver=letsencrypt'
      - 'traefik.http.services.api.loadbalancer.server.port=3333'
      - 'traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api'
      - 'traefik.http.middlewares.api-addprefix.addprefix.prefix=/api/v1'
      - 'traefik.http.routers.api.middlewares=api-stripprefix,api-addprefix'

  # queue:
  #   <<: *api
  #   command: sh -c "node src/bull.js"
  #   container_name: queue
  #   restart: always
  #   depends_on:
  #     - api

  mongodb:
    image: mongo:8-noble
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-mongodb}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-its-nestjs}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE:-its-nestjs}
    volumes:
      - ./tmp/mongo-data:/data/db
      - ./src/database/database.init.js:/docker-entrypoint-initdb.d/database.init.js:ro
    expose:
      - ${MONGO_PORT:-27017}

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - ./tmp/redis-data:/data
    restart: always
    expose:
      - ${REDIS_PORT:-6379}

networks:
  default:
    name: its-nestjs-network
    external: true
